/**
 * Code definitions (Pseudocode and JavaScript) for all supported algorithms.
 * Used by the Code Tracing panel during visualizer playback.
 */

export interface CodeLineItem {
  text: string;
  indent: number;
}

export interface AlgorithmCodeDefinition {
  algorithmId: string;
  pseudocode: CodeLineItem[];
  javascript?: CodeLineItem[];
}

export const algorithmCodes: Record<string, AlgorithmCodeDefinition> = {
  'bubble-sort': {
    algorithmId: 'bubble-sort',
    pseudocode: [
      { text: 'function bubbleSort(arr):', indent: 0 },
      { text: 'for i = 0 to n - 1:', indent: 1 },
      { text: 'for j = 0 to n - i - 2:', indent: 2 },
      { text: 'if arr[j] > arr[j + 1]:', indent: 3 },
      { text: 'swap(arr[j], arr[j + 1])', indent: 4 },
      { text: 'return arr', indent: 1 },
    ],
    javascript: [
      { text: 'function bubbleSort(arr) {', indent: 0 },
      { text: 'const n = arr.length;', indent: 1 },
      { text: 'for (let i = 0; i < n; i++) {', indent: 1 },
      { text: 'for (let j = 0; j < n - i - 1; j++) {', indent: 2 },
      { text: 'if (arr[j] > arr[j + 1]) {', indent: 3 },
      { text: '[arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];', indent: 4 },
      { text: '}', indent: 3 },
      { text: '}', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'insertion-sort': {
    algorithmId: 'insertion-sort',
    pseudocode: [
      { text: 'function insertionSort(arr):', indent: 0 },
      { text: 'for i = 1 to n - 1:', indent: 1 },
      { text: 'key = arr[i]', indent: 2 },
      { text: 'j = i - 1', indent: 2 },
      { text: 'while j >= 0 and arr[j] > key:', indent: 2 },
      { text: 'arr[j + 1] = arr[j]', indent: 3 },
      { text: 'j = j - 1', indent: 3 },
      { text: 'arr[j + 1] = key', indent: 2 },
      { text: 'return arr', indent: 1 },
    ],
    javascript: [
      { text: 'function insertionSort(arr) {', indent: 0 },
      { text: 'for (let i = 1; i < arr.length; i++) {', indent: 1 },
      { text: 'const key = arr[i];', indent: 2 },
      { text: 'let j = i - 1;', indent: 2 },
      { text: 'while (j >= 0 && arr[j] > key) {', indent: 2 },
      { text: 'arr[j + 1] = arr[j];', indent: 3 },
      { text: 'j--;', indent: 3 },
      { text: '}', indent: 2 },
      { text: 'arr[j + 1] = key;', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'selection-sort': {
    algorithmId: 'selection-sort',
    pseudocode: [
      { text: 'function selectionSort(arr):', indent: 0 },
      { text: 'for i = 0 to n - 2:', indent: 1 },
      { text: 'minIdx = i', indent: 2 },
      { text: 'for j = i + 1 to n - 1:', indent: 2 },
      { text: 'if arr[j] < arr[minIdx]:', indent: 3 },
      { text: 'minIdx = j', indent: 4 },
      { text: 'if minIdx != i: swap(arr[i], arr[minIdx])', indent: 2 },
      { text: 'return arr', indent: 1 },
    ],
    javascript: [
      { text: 'function selectionSort(arr) {', indent: 0 },
      { text: 'for (let i = 0; i < arr.length - 1; i++) {', indent: 1 },
      { text: 'let minIdx = i;', indent: 2 },
      { text: 'for (let j = i + 1; j < arr.length; j++) {', indent: 2 },
      { text: 'if (arr[j] < arr[minIdx]) {', indent: 3 },
      { text: 'minIdx = j;', indent: 4 },
      { text: '}', indent: 3 },
      { text: '}', indent: 2 },
      { text: 'if (minIdx !== i) {', indent: 2 },
      { text: '[arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];', indent: 3 },
      { text: '}', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'quick-sort': {
    algorithmId: 'quick-sort',
    pseudocode: [
      { text: 'function quickSort(arr, low, high):', indent: 0 },
      { text: 'if low < high:', indent: 1 },
      { text: 'pivot = arr[high]', indent: 2 },
      { text: 'i = low - 1', indent: 2 },
      { text: 'for j = low to high - 1:', indent: 2 },
      { text: 'if arr[j] < pivot:', indent: 3 },
      { text: 'i = i + 1; swap(arr[i], arr[j])', indent: 4 },
      { text: 'swap(arr[i + 1], arr[high])', indent: 2 },
      { text: 'quickSort(arr, low, i); quickSort(arr, i + 2, high)', indent: 2 },
    ],
    javascript: [
      { text: 'function quickSort(arr, low = 0, high = arr.length - 1) {', indent: 0 },
      { text: 'if (low < high) {', indent: 1 },
      { text: 'const pivot = arr[high];', indent: 2 },
      { text: 'let i = low - 1;', indent: 2 },
      { text: 'for (let j = low; j < high; j++) {', indent: 2 },
      { text: 'if (arr[j] < pivot) {', indent: 3 },
      { text: 'i++; [arr[i], arr[j]] = [arr[j], arr[i]];', indent: 4 },
      { text: '}', indent: 3 },
      { text: '}', indent: 2 },
      { text: '[arr[i + 1], arr[high]] = [arr[high], arr[i + 1]];', indent: 2 },
      { text: 'quickSort(arr, low, i);', indent: 2 },
      { text: 'quickSort(arr, i + 2, high);', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'merge-sort': {
    algorithmId: 'merge-sort',
    pseudocode: [
      { text: 'function mergeSort(arr, left, right):', indent: 0 },
      { text: 'if left < right:', indent: 1 },
      { text: 'mid = floor((left + right) / 2)', indent: 2 },
      { text: 'mergeSort(arr, left, mid)', indent: 2 },
      { text: 'mergeSort(arr, mid + 1, right)', indent: 2 },
      { text: 'merge(arr, left, mid, right)', indent: 2 },
      { text: 'function merge(arr, left, mid, right):', indent: 0 },
      { text: 'while i < len(L) and j < len(R):', indent: 1 },
      { text: 'if L[i] <= R[j]: arr[k] = L[i]; i++', indent: 2 },
      { text: 'else: arr[k] = R[j]; j++', indent: 2 },
    ],
    javascript: [
      { text: 'function mergeSort(arr, left = 0, right = arr.length - 1) {', indent: 0 },
      { text: 'if (left < right) {', indent: 1 },
      { text: 'const mid = Math.floor((left + right) / 2);', indent: 2 },
      { text: 'mergeSort(arr, left, mid);', indent: 2 },
      { text: 'mergeSort(arr, mid + 1, right);', indent: 2 },
      { text: 'merge(arr, left, mid, right);', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'linear-search': {
    algorithmId: 'linear-search',
    pseudocode: [
      { text: 'function linearSearch(arr, target):', indent: 0 },
      { text: 'for i = 0 to n - 1:', indent: 1 },
      { text: 'if arr[i] == target:', indent: 2 },
      { text: 'return i // Target found', indent: 3 },
      { text: 'return -1 // Not found', indent: 1 },
    ],
    javascript: [
      { text: 'function linearSearch(arr, target) {', indent: 0 },
      { text: 'for (let i = 0; i < arr.length; i++) {', indent: 1 },
      { text: 'if (arr[i] === target) {', indent: 2 },
      { text: 'return i;', indent: 3 },
      { text: '}', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return -1;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'binary-search': {
    algorithmId: 'binary-search',
    pseudocode: [
      { text: 'function binarySearch(arr, target):', indent: 0 },
      { text: 'low = 0, high = n - 1', indent: 1 },
      { text: 'while low <= high:', indent: 1 },
      { text: 'mid = floor((low + high) / 2)', indent: 2 },
      { text: 'if arr[mid] == target: return mid', indent: 2 },
      { text: 'else if arr[mid] < target: low = mid + 1', indent: 2 },
      { text: 'else: high = mid - 1', indent: 2 },
      { text: 'return -1 // Not found', indent: 1 },
    ],
    javascript: [
      { text: 'function binarySearch(arr, target) {', indent: 0 },
      { text: 'let low = 0, high = arr.length - 1;', indent: 1 },
      { text: 'while (low <= high) {', indent: 1 },
      { text: 'const mid = Math.floor((low + high) / 2);', indent: 2 },
      { text: 'if (arr[mid] === target) return mid;', indent: 2 },
      { text: 'else if (arr[mid] < target) low = mid + 1;', indent: 2 },
      { text: 'else high = mid - 1;', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return -1;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'shell-sort': {
    algorithmId: 'shell-sort',
    pseudocode: [
      { text: 'function shellSort(arr):', indent: 0 },
      { text: 'gap = floor(n / 2)', indent: 1 },
      { text: 'while gap > 0:', indent: 1 },
      { text: 'for i = gap to n - 1:', indent: 2 },
      { text: 'temp = arr[i], j = i', indent: 3 },
      { text: 'while j >= gap and arr[j - gap] > temp:', indent: 3 },
      { text: 'arr[j] = arr[j - gap]; j -= gap', indent: 4 },
      { text: 'arr[j] = temp', indent: 3 },
      { text: 'gap = floor(gap / 2)', indent: 2 },
      { text: 'return arr', indent: 1 },
    ],
    javascript: [
      { text: 'function shellSort(arr) {', indent: 0 },
      { text: 'const n = arr.length;', indent: 1 },
      {
        text: 'for (let gap = Math.floor(n / 2); gap > 0; gap = Math.floor(gap / 2)) {',
        indent: 1,
      },
      { text: 'for (let i = gap; i < n; i++) {', indent: 2 },
      { text: 'const temp = arr[i]; let j = i;', indent: 3 },
      { text: 'while (j >= gap && arr[j - gap] > temp) {', indent: 3 },
      { text: 'arr[j] = arr[j - gap]; j -= gap;', indent: 4 },
      { text: '}', indent: 3 },
      { text: 'arr[j] = temp;', indent: 3 },
      { text: '}', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'heap-sort': {
    algorithmId: 'heap-sort',
    pseudocode: [
      { text: 'function heapSort(arr):', indent: 0 },
      { text: 'buildMaxHeap(arr)', indent: 1 },
      { text: 'for i = n - 1 down to 1:', indent: 1 },
      { text: 'swap(arr[0], arr[i])', indent: 2 },
      { text: 'maxHeapify(arr, i, 0)', indent: 2 },
      { text: 'function maxHeapify(arr, n, i):', indent: 0 },
      { text: 'largest = i, l = 2*i + 1, r = 2*i + 2', indent: 1 },
      { text: 'if l < n and arr[l] > arr[largest]: largest = l', indent: 1 },
      { text: 'if r < n and arr[r] > arr[largest]: largest = r', indent: 1 },
      { text: 'if largest != i: swap(arr[i], arr[largest]); maxHeapify(...)', indent: 1 },
    ],
    javascript: [
      { text: 'function heapSort(arr) {', indent: 0 },
      { text: 'const n = arr.length;', indent: 1 },
      { text: 'for (let i = Math.floor(n / 2) - 1; i >= 0; i--) heapify(arr, n, i);', indent: 1 },
      { text: 'for (let i = n - 1; i > 0; i--) {', indent: 1 },
      { text: '[arr[0], arr[i]] = [arr[i], arr[0]];', indent: 2 },
      { text: 'heapify(arr, i, 0);', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  bogosort: {
    algorithmId: 'bogosort',
    pseudocode: [
      { text: 'function bogosort(arr):', indent: 0 },
      { text: 'while not isSorted(arr):', indent: 1 },
      { text: 'shuffle(arr)', indent: 2 },
      { text: 'attempts++', indent: 2 },
      { text: 'return arr', indent: 1 },
    ],
    javascript: [
      { text: 'function bogosort(arr) {', indent: 0 },
      { text: 'while (!isSorted(arr)) {', indent: 1 },
      { text: 'shuffle(arr);', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'return arr;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
  'n-queens': {
    algorithmId: 'n-queens',
    pseudocode: [
      { text: 'function solve(row):', indent: 0 },
      { text: 'if row == n: return true', indent: 1 },
      { text: 'for col = 0 to n - 1:', indent: 1 },
      { text: 'if isSafe(row, col):', indent: 2 },
      { text: 'board[row] = col', indent: 3 },
      { text: 'if solve(row + 1): return true', indent: 3 },
      { text: 'board[row] = -1 // backtrack', indent: 3 },
      { text: 'return false', indent: 1 },
    ],
    javascript: [
      { text: 'function solveNQueens(n) {', indent: 0 },
      { text: 'const board = Array(n).fill(-1);', indent: 1 },
      { text: 'function solve(row) {', indent: 1 },
      { text: 'if (row === n) return true;', indent: 2 },
      { text: 'for (let col = 0; col < n; col++) {', indent: 2 },
      { text: 'if (isSafe(row, col, board)) {', indent: 3 },
      { text: 'board[row] = col;', indent: 4 },
      { text: 'if (solve(row + 1)) return true;', indent: 4 },
      { text: 'board[row] = -1;', indent: 4 },
      { text: '}', indent: 3 },
      { text: '}', indent: 2 },
      { text: 'return false;', indent: 2 },
      { text: '}', indent: 1 },
      { text: 'solve(0);', indent: 1 },
      { text: 'return board;', indent: 1 },
      { text: '}', indent: 0 },
    ],
  },
};

export function getAlgorithmCode(algorithmId: string): AlgorithmCodeDefinition | undefined {
  return algorithmCodes[algorithmId];
}
