/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'learning-events': LearningEvent;
    'algorithm-progress': AlgorithmProgress;
    courses: Course;
    'course-progress': CourseProgress;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'learning-events': LearningEventsSelect<false> | LearningEventsSelect<true>;
    'algorithm-progress': AlgorithmProgressSelect<false> | AlgorithmProgressSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'admin' | 'user';
  bio?: string | null;
  /**
   * Profile image URL (synced from social providers).
   */
  imageUrl?: string | null;
  /**
   * Algorithms the user has already mastered.
   */
  completedAlgorithms?:
    | (
        | 'bubble-sort'
        | 'insertion-sort'
        | 'selection-sort'
        | 'shell-sort'
        | 'merge-sort'
        | 'quick-sort'
        | 'heap-sort'
        | 'linear-search'
        | 'binary-search'
        | 'n-queens'
        | 'bogosort'
      )[]
    | null;
  /**
   * Persistent state of the algorithm visualizer for each algorithm.
   */
  visualizerProgress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Aggregated learning statistics across all algorithms.
   */
  learningStats?: {
    totalTimeSpentMs?: number | null;
    totalAlgorithmsStarted?: number | null;
    totalAlgorithmsCompleted?: number | null;
    totalControlAttempts?: number | null;
    totalCreateAttempts?: number | null;
    totalAliveAttempts?: number | null;
    totalMistakes?: number | null;
    totalHintsUsed?: number | null;
    averageScore?: number | null;
    currentStreak?: number | null;
    longestStreak?: number | null;
    lastActiveDate?: string | null;
    preferredSpeed?: number | null;
  };
  authProvider?: ('email' | 'google' | 'facebook' | 'discord' | 'github') | null;
  authProviderId?: string | null;
  lastResetRequest?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-events".
 */
export interface LearningEvent {
  id: number;
  user: number | User;
  /**
   * e.g. bubble-sort, insertion-sort
   */
  algorithmId: string;
  tab: 'video' | 'animation' | 'control' | 'create' | 'alive';
  /**
   * e.g. tab_enter, animation_play, control_compare, create_blank_attempt, alive_code_submit
   */
  eventType: string;
  /**
   * Arbitrary event-specific payload (indices, values, scores, etc.)
   */
  eventData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * UUID grouping events within a single learning session.
   */
  sessionId: string;
  /**
   * Milliseconds since the previous event in this session.
   */
  durationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "algorithm-progress".
 */
export interface AlgorithmProgress {
  id: number;
  user: number | User;
  algorithmId: string;
  videoWatched?: boolean | null;
  videoWatchTimeMs?: number | null;
  videoCompletedAt?: string | null;
  animationCompleted?: boolean | null;
  animationTotalTimeMs?: number | null;
  animationPlayCount?: number | null;
  animationCompletedAt?: string | null;
  controlCompleted?: boolean | null;
  controlBestScore?: number | null;
  controlMistakes?: number | null;
  controlHintsUsed?: number | null;
  controlAttempts?: number | null;
  controlBestTimeMs?: number | null;
  controlCompletedAt?: string | null;
  createCompleted?: boolean | null;
  /**
   * Whether the user activated card-drag help.
   */
  createHelpUsed?: boolean | null;
  createAttempts?: number | null;
  /**
   * Number of blanks answered correctly on first attempt.
   */
  createBlanksCorrectFirst?: number | null;
  createBlanksTotal?: number | null;
  createTotalTimeMs?: number | null;
  createCompletedAt?: string | null;
  aliveCompleted?: boolean | null;
  /**
   * Whether the user switched to node-block mode.
   */
  aliveHelpUsed?: boolean | null;
  aliveCodeSubmissions?: number | null;
  /**
   * The last code the user submitted.
   */
  aliveLastCode?: string | null;
  aliveBestScore?: number | null;
  aliveTotalTimeMs?: number | null;
  aliveCompletedAt?: string | null;
  /**
   * Weighted % across all 5 tabs (0–100).
   */
  overallProgress?: number | null;
  totalTimeSpentMs?: number | null;
  lastActivityAt?: string | null;
  firstStartedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable course blueprints with phases, mascot behavior, confidence prompts, and complexity guidance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Pick the bubble sort starter template or start from a blank custom course.
   */
  preset: 'bubble-sort' | 'custom';
  title: string;
  /**
   * Used in the public URL, for example bubble-sort.
   */
  slug: string;
  /**
   * The canonical algorithm or topic id that the course teaches.
   */
  algorithmId: string;
  summary: string;
  /**
   * A short line used on the course landing page hero.
   */
  heroTagline?: string | null;
  /**
   * Emoji or short icon token for the course card.
   */
  icon?: string | null;
  /**
   * Primary accent color used in cards and buttons.
   */
  accentColor?: string | null;
  /**
   * Asset filename from /public/assets.
   */
  illustrationAsset?: string | null;
  /**
   * Approximate total learning time in minutes.
   */
  estimatedMinutes: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  /**
   * Why this course deserves a featured card on the course index.
   */
  featuredReason?: string | null;
  /**
   * Short labels such as Video intuition, Drag-and-drop, or Debugging.
   */
  learningModes?: string[] | null;
  /**
   * Per-course mascot configuration and trigger copy.
   */
  mascot: {
    name: string;
    /**
     * Preset key for course-specific mascot styling.
     */
    preset?: string | null;
    asset?: string | null;
    accentColor?: string | null;
    idleTriggerSeconds?: number | null;
    mistakeTriggerCount?: number | null;
    summonLabel?: string | null;
    /**
     * Message used when the learner stalls for a while.
     */
    idlePrompt?: string | null;
    /**
     * Message used after repeated wrong attempts.
     */
    mistakePrompt?: string | null;
    confidencePrompt?: string | null;
  };
  /**
   * Confidence-based learning copy and reward configuration.
   */
  confidenceLearning?: {
    enabled?: boolean | null;
    promptLabel?: string | null;
    praiseText?: string | null;
    correctionText?: string | null;
    rewardBadge?: string | null;
    /**
     * Probability of occasionally prompting a confidence check.
     */
    idleCheckProbability?: number | null;
  };
  /**
   * Complexity notes, diagrams, and mistake impact details.
   */
  complexity?: {
    timeComplexity?: string | null;
    spaceComplexity?: string | null;
    bestCase?: string | null;
    averageCase?: string | null;
    worstCase?: string | null;
    diagramChoices?:
      | {
          label: string;
          explanation: string;
          impact: string;
          correct?: boolean | null;
          id?: string | null;
        }[]
      | null;
    mistakeImpacts?:
      | {
          label: string;
          impact: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Ordered course phases; these are the main building blocks of the course.
   */
  phases?:
    | {
        phaseId: string;
        title: string;
        kind: 'motivation' | 'guided-visualization' | 'code-building' | 'analysis' | 'final-challenge';
        /**
         * Which existing algorithm learning view this phase should embed.
         */
        sourceView: 'video' | 'animation' | 'control' | 'create' | 'alive';
        /**
         * Algorithm id to pull the learning step from, such as bubble-sort.
         */
        sourceAlgorithmId?: string | null;
        summary: string;
        objective: string;
        durationMinutes: number;
        /**
         * Prompt shown after the learner answers or before a checkpoint.
         */
        confidencePrompt?: string | null;
        mascotLine?: string | null;
        taskTitle: string;
        taskPrompt: string;
        successCopy: string;
        hintCopy: string;
        rewardLabel: string;
        tips?:
          | {
              tip: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Final debugging and quiz challenge configuration.
   */
  finalChallenge: {
    title?: string | null;
    debuggingPrompt: string;
    quizPrompt: string;
    mentorPolicy: string;
    badge?: string | null;
  };
  /**
   * Optional authoring notes for the next course blueprint.
   */
  nextSteps?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: number;
  user: number | User;
  courseId: string;
  activePhaseIndex?: number | null;
  completedPhases?: string[] | null;
  lastConfidenceRating?: string | null;
  phaseResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  points?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'learning-events';
        value: number | LearningEvent;
      } | null)
    | ({
        relationTo: 'algorithm-progress';
        value: number | AlgorithmProgress;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-progress';
        value: number | CourseProgress;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  bio?: T;
  imageUrl?: T;
  completedAlgorithms?: T;
  visualizerProgress?: T;
  learningStats?:
    | T
    | {
        totalTimeSpentMs?: T;
        totalAlgorithmsStarted?: T;
        totalAlgorithmsCompleted?: T;
        totalControlAttempts?: T;
        totalCreateAttempts?: T;
        totalAliveAttempts?: T;
        totalMistakes?: T;
        totalHintsUsed?: T;
        averageScore?: T;
        currentStreak?: T;
        longestStreak?: T;
        lastActiveDate?: T;
        preferredSpeed?: T;
      };
  authProvider?: T;
  authProviderId?: T;
  lastResetRequest?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-events_select".
 */
export interface LearningEventsSelect<T extends boolean = true> {
  user?: T;
  algorithmId?: T;
  tab?: T;
  eventType?: T;
  eventData?: T;
  sessionId?: T;
  durationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "algorithm-progress_select".
 */
export interface AlgorithmProgressSelect<T extends boolean = true> {
  user?: T;
  algorithmId?: T;
  videoWatched?: T;
  videoWatchTimeMs?: T;
  videoCompletedAt?: T;
  animationCompleted?: T;
  animationTotalTimeMs?: T;
  animationPlayCount?: T;
  animationCompletedAt?: T;
  controlCompleted?: T;
  controlBestScore?: T;
  controlMistakes?: T;
  controlHintsUsed?: T;
  controlAttempts?: T;
  controlBestTimeMs?: T;
  controlCompletedAt?: T;
  createCompleted?: T;
  createHelpUsed?: T;
  createAttempts?: T;
  createBlanksCorrectFirst?: T;
  createBlanksTotal?: T;
  createTotalTimeMs?: T;
  createCompletedAt?: T;
  aliveCompleted?: T;
  aliveHelpUsed?: T;
  aliveCodeSubmissions?: T;
  aliveLastCode?: T;
  aliveBestScore?: T;
  aliveTotalTimeMs?: T;
  aliveCompletedAt?: T;
  overallProgress?: T;
  totalTimeSpentMs?: T;
  lastActivityAt?: T;
  firstStartedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  preset?: T;
  title?: T;
  slug?: T;
  algorithmId?: T;
  summary?: T;
  heroTagline?: T;
  icon?: T;
  accentColor?: T;
  illustrationAsset?: T;
  estimatedMinutes?: T;
  difficulty?: T;
  featuredReason?: T;
  learningModes?: T;
  mascot?:
    | T
    | {
        name?: T;
        preset?: T;
        asset?: T;
        accentColor?: T;
        idleTriggerSeconds?: T;
        mistakeTriggerCount?: T;
        summonLabel?: T;
        idlePrompt?: T;
        mistakePrompt?: T;
        confidencePrompt?: T;
      };
  confidenceLearning?:
    | T
    | {
        enabled?: T;
        promptLabel?: T;
        praiseText?: T;
        correctionText?: T;
        rewardBadge?: T;
        idleCheckProbability?: T;
      };
  complexity?:
    | T
    | {
        timeComplexity?: T;
        spaceComplexity?: T;
        bestCase?: T;
        averageCase?: T;
        worstCase?: T;
        diagramChoices?:
          | T
          | {
              label?: T;
              explanation?: T;
              impact?: T;
              correct?: T;
              id?: T;
            };
        mistakeImpacts?:
          | T
          | {
              label?: T;
              impact?: T;
              id?: T;
            };
      };
  phases?:
    | T
    | {
        phaseId?: T;
        title?: T;
        kind?: T;
        sourceView?: T;
        sourceAlgorithmId?: T;
        summary?: T;
        objective?: T;
        durationMinutes?: T;
        confidencePrompt?: T;
        mascotLine?: T;
        taskTitle?: T;
        taskPrompt?: T;
        successCopy?: T;
        hintCopy?: T;
        rewardLabel?: T;
        tips?:
          | T
          | {
              tip?: T;
              id?: T;
            };
        id?: T;
      };
  finalChallenge?:
    | T
    | {
        title?: T;
        debuggingPrompt?: T;
        quizPrompt?: T;
        mentorPolicy?: T;
        badge?: T;
      };
  nextSteps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  user?: T;
  courseId?: T;
  activePhaseIndex?: T;
  completedPhases?: T;
  lastConfidenceRating?: T;
  phaseResults?: T;
  points?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}