/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    users: User;
    'learning-events': LearningEvent;
    'algorithm-progress': AlgorithmProgress;
    'course-progress': CourseProgress;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'learning-events': LearningEventsSelect<false> | LearningEventsSelect<true>;
    'algorithm-progress': AlgorithmProgressSelect<false> | AlgorithmProgressSelect<true>;
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hu' | 'en' | 'ro') | ('hu' | 'en' | 'ro')[];
  globals: {};
  globalsSelect: {};
  locale: 'hu' | 'en' | 'ro';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Reusable course blueprints with phases, mascot behavior, confidence prompts, and complexity guidance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * A kurzus teljes neve (pl. Buborékrendezés alapjai).
   */
  title: string;
  /**
   * A kurzus azonosítója az URL-ben (pl. bubble-sort-basics).
   */
  slug: string;
  /**
   * Rővid összefoglaló szöveg, ami a kurzuslistában jelenik meg.
   */
  summary: string;
  /**
   * Egy rövid szlogen, ami a kurzus kezdőoldalának fejlécében látható.
   */
  heroTagline?: string | null;
  /**
   * Emoji vagy ikon kód a kurzus kártyájához.
   */
  icon?: string | null;
  /**
   * A kurzus gombjainak és UI elemeinek elsődleges szine.
   */
  accentColor?: string | null;
  /**
   * A kurzus fejlécében megjelenő illusztráció fájlneve.
   */
  illustrationAsset?: string | null;
  /**
   * A kurzus elvégzéséhez szükséges becsült idő percekben.
   */
  estimatedMinutes: number;
  /**
   * A kurzus nehézségi szintje.
   */
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  /**
   * Per-course mascot configuration and trigger copy.
   */
  mascot: {
    /**
     * Ki/Bekapcsolja a kabalát a teljes kurzusra.
     */
    enabled?: boolean | null;
    /**
     * A kabala neve (pl. Bubi). Ez jelenik meg a szövegbuborékok felett.
     */
    name: string;
    /**
     * A kabala vizuális megjelenése (választható illusztráció).
     */
    asset?: string | null;
    /**
     * A kabala szövegbuborékainak és UI elemeinek egyedi színe.
     */
    accentColor?: string | null;
    /**
     * Hány másodperc inaktivitás után szólaljon meg a kabala automatikusan.
     */
    idleTriggerSeconds?: number | null;
    /**
     * Hány egymást követő rossz válasz után ajánljon fel proaktív segítséget.
     */
    mistakeTriggerCount?: number | null;
    /**
     * A gomb felirata, amivel a kabalát bármikor manuálisan elő lehet hívni.
     */
    summonLabel?: string | null;
    /**
     * Rövid figyelemfelkeltő üzenet inaktivitás esetén (pl. "Segíthetek a következő lépésben?").
     */
    idlePrompt?: string | null;
    /**
     * Rövid üzenet gyanúsan sok hiba esetén, mielőtt megnyílna a tipp-felület.
     */
    mistakePrompt?: string | null;
    /**
     * Üdvözlő üzenetek a kurzus indításakor (véletlenszerűen választva).
     */
    welcomeMessages?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Üzenetek arra az esetre, ha a felhasználó magabiztos volt, de elrontotta a feladatot.
     */
    overconfidentMessages?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Dicsérő, bíztató üzenetek sikeres válaszsorozatok (streak) esetén.
     */
    streakMessages?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Ordered course phases; these are the main building blocks of the course.
   */
  phases?:
    | {
        /**
         * Egyedi technikai azonosító (pl. bubble-sort-intro). Használd a javaslat gombot!
         */
        phaseId: string;
        /**
         * A fázis címe a tanuló felé.
         */
        title: string;
        /**
         * Az algoritmus technikai neve, amiből a rendszer merít (pl. bubble-sort).
         */
        sourceAlgorithmId: string;
        /**
         * Az interaktív felület típusa (videó, kvíz, animáció stb.).
         */
        sourceView:
          | 'video'
          | 'video-custom'
          | 'animation'
          | 'control'
          | 'create'
          | 'alive'
          | 'quiz'
          | 'match'
          | 'order'
          | 'debug'
          | 'gap-fill'
          | 'info'
          | 'final-challenge';
        /**
         * Fázis leírása: miről szól ez a rész?
         */
        summary: string;
        /**
         * Opcionális: A kabala egyedi bátorító mondata.
         */
        mascotLine?: string | null;
        /**
         * Opcionális: Egyedi üzenet sok hiba esetén (pl. "Látom elakadtál ennél a résznél...").
         */
        mascotMistakeLine?: string | null;
        /**
         * A konkrét szakmai segítség/tipp a fázishoz.
         */
        hintCopy?: string | null;
        /**
         * Tipp vagy bátorítás, ha sokáig nem történik semmi a fázisban.
         */
        idleHelp?: string | null;
        /**
         * Legyen-e magabiztosság ellenőrzés (kérdőív) a fázis befejezése után?
         */
        askConfidence?: boolean | null;
        /**
         * A fázisért kapható maximális pontszám. A create/alive nézetben részleges pontot is kaphat a tanuló.
         */
        maxPoints?: number | null;
        /**
         * Információs szöveg (csak info nézetnél látszik).
         */
        infoContent?: string | null;
        /**
         * YouTube Video ID (pl. d995_u3q6mE). Csak egyéni videó esetén.
         */
        customVideoId?: string | null;
        /**
         * Kvíz kérdések (csak kvíz nézetnél látszik).
         */
        quiz?:
          | {
              question: string;
              options?:
                | {
                    option: string;
                    id?: string | null;
                  }[]
                | null;
              correctIndex: number;
              explanation: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Párosító feladat (bal és jobb oldal összekötése).
         */
        matching?:
          | {
              left: string;
              right: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Sorrendbe rendezés feladat.
         */
        ordering?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * A hibás kód, amit ki kell javítani.
         */
        debugCode?: string | null;
        /**
         * Az elvárt kód a javítás után.
         */
        expectedCode?: string | null;
        /**
         * A szöveg hiányzó részekkel (pl: "A buborékrendezés {{gap}} algoritmus").
         */
        gapFillContent?: string | null;
        /**
         * Választható szavak a hiányzó részekhez.
         */
        gapFillOptions?:
          | {
              option: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'admin' | 'editor' | 'user';
  bio?: string | null;
  /**
   * Profile image URL (synced from social providers).
   */
  imageUrl?: string | null;
  /**
   * Engedélyezze vagy tiltsa le a segítő kabalaállat megjelenését.
   */
  mascotEnabled?: boolean | null;
  /**
   * Algorithms the user has already mastered.
   */
  completedAlgorithms?:
    | (
        | 'bubble-sort'
        | 'insertion-sort'
        | 'selection-sort'
        | 'shell-sort'
        | 'merge-sort'
        | 'quick-sort'
        | 'heap-sort'
        | 'linear-search'
        | 'binary-search'
        | 'n-queens'
        | 'bogosort'
      )[]
    | null;
  /**
   * Kurzusok, amiket a felhasználó már teljesített.
   */
  completedCourses?: (number | Course)[] | null;
  /**
   * Persistent state of the algorithm visualizer for each algorithm.
   */
  visualizerProgress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Aggregated learning statistics across all algorithms.
   */
  learningStats?: {
    totalTimeSpentMs?: number | null;
    totalAlgorithmsStarted?: number | null;
    totalAlgorithmsCompleted?: number | null;
    totalControlAttempts?: number | null;
    totalCreateAttempts?: number | null;
    totalAliveAttempts?: number | null;
    totalMistakes?: number | null;
    totalHintsUsed?: number | null;
    averageScore?: number | null;
    currentStreak?: number | null;
    longestStreak?: number | null;
    lastActiveDate?: string | null;
    preferredSpeed?: number | null;
  };
  authProvider?: ('email' | 'google' | 'facebook' | 'discord' | 'github') | null;
  authProviderId?: string | null;
  lastResetRequest?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-events".
 */
export interface LearningEvent {
  id: number;
  user: number | User;
  /**
   * e.g. bubble-sort, insertion-sort
   */
  algorithmId: string;
  tab: 'video' | 'animation' | 'control' | 'create' | 'alive';
  /**
   * e.g. tab_enter, animation_play, control_compare, create_blank_attempt, alive_code_submit
   */
  eventType: string;
  /**
   * Arbitrary event-specific payload (indices, values, scores, etc.)
   */
  eventData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * UUID grouping events within a single learning session.
   */
  sessionId: string;
  /**
   * Milliseconds since the previous event in this session.
   */
  durationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "algorithm-progress".
 */
export interface AlgorithmProgress {
  id: number;
  user: number | User;
  algorithmId: string;
  videoWatched?: boolean | null;
  videoWatchTimeMs?: number | null;
  videoCompletedAt?: string | null;
  animationCompleted?: boolean | null;
  animationTotalTimeMs?: number | null;
  animationPlayCount?: number | null;
  animationCompletedAt?: string | null;
  controlCompleted?: boolean | null;
  controlBestScore?: number | null;
  controlMistakes?: number | null;
  controlHintsUsed?: number | null;
  controlAttempts?: number | null;
  controlBestTimeMs?: number | null;
  controlCompletedAt?: string | null;
  createCompleted?: boolean | null;
  /**
   * Whether the user activated card-drag help.
   */
  createHelpUsed?: boolean | null;
  createAttempts?: number | null;
  /**
   * Number of blanks answered correctly on first attempt.
   */
  createBlanksCorrectFirst?: number | null;
  createBlanksTotal?: number | null;
  createTotalTimeMs?: number | null;
  createCompletedAt?: string | null;
  aliveCompleted?: boolean | null;
  /**
   * Whether the user switched to node-block mode.
   */
  aliveHelpUsed?: boolean | null;
  aliveCodeSubmissions?: number | null;
  /**
   * The last code the user submitted.
   */
  aliveLastCode?: string | null;
  aliveBestScore?: number | null;
  aliveTotalTimeMs?: number | null;
  aliveCompletedAt?: string | null;
  /**
   * Weighted % across all 5 tabs (0–100).
   */
  overallProgress?: number | null;
  totalTimeSpentMs?: number | null;
  lastActivityAt?: string | null;
  firstStartedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: number;
  user: number | User;
  courseId: string;
  activePhaseIndex?: number | null;
  completedPhases?: string[] | null;
  lastConfidenceRating?: string | null;
  phaseResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  points?: number | null;
  isCompleted?: boolean | null;
  totalTimeMs?: number | null;
  totalMistakes?: number | null;
  mascotInteractionsTotal?: number | null;
  /**
   * History of confidence ratings per phase
   */
  confidenceResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  firstStartedAt?: string | null;
  lastActivityAt?: string | null;
  /**
   * Comprehensive per-phase telemetry (time, results, mistakes, mascot help, etc.)
   */
  detailedStats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-phase scoring: { [phaseId]: { earned: number, max: number, helpUsed: boolean, partial: boolean } }
   */
  phasePoints?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'learning-events';
        value: number | LearningEvent;
      } | null)
    | ({
        relationTo: 'algorithm-progress';
        value: number | AlgorithmProgress;
      } | null)
    | ({
        relationTo: 'course-progress';
        value: number | CourseProgress;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  heroTagline?: T;
  icon?: T;
  accentColor?: T;
  illustrationAsset?: T;
  estimatedMinutes?: T;
  difficulty?: T;
  mascot?:
    | T
    | {
        enabled?: T;
        name?: T;
        asset?: T;
        accentColor?: T;
        idleTriggerSeconds?: T;
        mistakeTriggerCount?: T;
        summonLabel?: T;
        idlePrompt?: T;
        mistakePrompt?: T;
        welcomeMessages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        overconfidentMessages?:
          | T
          | {
              text?: T;
              id?: T;
            };
        streakMessages?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  phases?:
    | T
    | {
        phaseId?: T;
        title?: T;
        sourceAlgorithmId?: T;
        sourceView?: T;
        summary?: T;
        mascotLine?: T;
        mascotMistakeLine?: T;
        hintCopy?: T;
        idleHelp?: T;
        askConfidence?: T;
        maxPoints?: T;
        infoContent?: T;
        customVideoId?: T;
        quiz?:
          | T
          | {
              question?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              correctIndex?: T;
              explanation?: T;
              id?: T;
            };
        matching?:
          | T
          | {
              left?: T;
              right?: T;
              id?: T;
            };
        ordering?:
          | T
          | {
              text?: T;
              id?: T;
            };
        debugCode?: T;
        expectedCode?: T;
        gapFillContent?: T;
        gapFillOptions?:
          | T
          | {
              option?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  bio?: T;
  imageUrl?: T;
  mascotEnabled?: T;
  completedAlgorithms?: T;
  completedCourses?: T;
  visualizerProgress?: T;
  learningStats?:
    | T
    | {
        totalTimeSpentMs?: T;
        totalAlgorithmsStarted?: T;
        totalAlgorithmsCompleted?: T;
        totalControlAttempts?: T;
        totalCreateAttempts?: T;
        totalAliveAttempts?: T;
        totalMistakes?: T;
        totalHintsUsed?: T;
        averageScore?: T;
        currentStreak?: T;
        longestStreak?: T;
        lastActiveDate?: T;
        preferredSpeed?: T;
      };
  authProvider?: T;
  authProviderId?: T;
  lastResetRequest?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-events_select".
 */
export interface LearningEventsSelect<T extends boolean = true> {
  user?: T;
  algorithmId?: T;
  tab?: T;
  eventType?: T;
  eventData?: T;
  sessionId?: T;
  durationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "algorithm-progress_select".
 */
export interface AlgorithmProgressSelect<T extends boolean = true> {
  user?: T;
  algorithmId?: T;
  videoWatched?: T;
  videoWatchTimeMs?: T;
  videoCompletedAt?: T;
  animationCompleted?: T;
  animationTotalTimeMs?: T;
  animationPlayCount?: T;
  animationCompletedAt?: T;
  controlCompleted?: T;
  controlBestScore?: T;
  controlMistakes?: T;
  controlHintsUsed?: T;
  controlAttempts?: T;
  controlBestTimeMs?: T;
  controlCompletedAt?: T;
  createCompleted?: T;
  createHelpUsed?: T;
  createAttempts?: T;
  createBlanksCorrectFirst?: T;
  createBlanksTotal?: T;
  createTotalTimeMs?: T;
  createCompletedAt?: T;
  aliveCompleted?: T;
  aliveHelpUsed?: T;
  aliveCodeSubmissions?: T;
  aliveLastCode?: T;
  aliveBestScore?: T;
  aliveTotalTimeMs?: T;
  aliveCompletedAt?: T;
  overallProgress?: T;
  totalTimeSpentMs?: T;
  lastActivityAt?: T;
  firstStartedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  user?: T;
  courseId?: T;
  activePhaseIndex?: T;
  completedPhases?: T;
  lastConfidenceRating?: T;
  phaseResults?: T;
  points?: T;
  isCompleted?: T;
  totalTimeMs?: T;
  totalMistakes?: T;
  mascotInteractionsTotal?: T;
  confidenceResults?: T;
  firstStartedAt?: T;
  lastActivityAt?: T;
  detailedStats?: T;
  phasePoints?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}